language: node_js
node_js:
  - "16.5.0"
before_script:
  - npm install
script: npm run build
deploy:
  local-dir: dist/top-collegues
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false